method: texnet
inherit_from: configs/singleview/texfields/chairs.yaml
data:
  path_shapes: data/demo
  dataset_imgs_type: image_folder
  img_size: 256
model:
  model_url:
generation:
  batch_size: 1
test:
  model_file: model_best.pt
  vis_dir: 'out/demo'
  dataset_split: 'test_vis' 
  with_occnet: False
  generation_mode: 'HD'
